# Generated by Django 4.2.27 on 2025-12-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meðlimur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafn', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='skodun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skodun', models.CharField(choices=[('0', 'Hatar'), ('1', 'Mislíkar'), ('2', 'Hlutlaus'), ('3', 'Líkar'), ('4', 'Elskar')], max_length=1)),
                ('athugasemd', models.TextField()),
                ('medlimur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meðlimir.meðlimur')),
            ],
        ),
    ]
