# Generated by Django 4.2.27 on 2025-12-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uppskrift', '0001_initial'),
        ('meðlimir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skodun',
            name='uppskrift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uppskrift.uppskrift'),
        ),
    ]
