# Generated by Django 4.2.27 on 2025-12-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meðlimir', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meðlimur',
            options={'verbose_name_plural': 'Meðlimir'},
        ),
    ]
