# Generated by Django 4.2.27 on 2025-12-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uppskrift', '0005_alter_uppskrift_flokkar_alter_uppskrift_skodanir'),
        ('meðlimir', '0003_alter_meðlimur_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meðlimur',
            new_name='Medlimur',
        ),
    ]
