# Generated by Django 4.2.27 on 2025-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flokkar', '0001_initial'),
        ('meðlimir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uppskrift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafn', models.CharField(max_length=64)),
                ('innihaldsefni', models.TextField()),
                ('uppskrift', models.TextField()),
                ('athugasemdir', models.TextField()),
                ('flokkar', models.ManyToManyField(to='flokkar.flokkur')),
                ('skodanir', models.ManyToManyField(related_name='medlimaskodanir', through='meðlimir.skodun', to='meðlimir.meðlimur')),
            ],
        ),
    ]
