# Generated by Django 4.2.27 on 2025-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uppskrift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uppskrift',
            options={'verbose_name_plural': 'Uppskriftir'},
        ),
        migrations.AddField(
            model_name='uppskrift',
            name='slug',
            field=models.SlugField(default='morgunkorn', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
