# Generated by Django 4.2.27 on 2025-12-11 23:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('uppskrift', '0002_alter_uppskrift_options_uppskrift_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppskrift',
            name='innihaldsefni',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='uppskrift',
            name='uppskrift',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
