# Generated by Django 4.2.27 on 2025-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meðlimir', '0003_alter_meðlimur_options'),
        ('flokkar', '0002_alter_flokkur_options_flokkur_yfirflokkur'),
        ('uppskrift', '0003_alter_uppskrift_innihaldsefni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uppskrift',
            name='uppruni',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='uppskrift',
            name='athugasemdir',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uppskrift',
            name='flokkar',
            field=models.ManyToManyField(blank=True, null=True, to='flokkar.flokkur'),
        ),
        migrations.AlterField(
            model_name='uppskrift',
            name='skodanir',
            field=models.ManyToManyField(blank=True, null=True, related_name='medlimaskodanir', through='meðlimir.skodun', to='meðlimir.meðlimur'),
        ),
    ]
