# Generated by Django 4.2.27 on 2025-12-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flokkar', '0002_alter_flokkur_options_flokkur_yfirflokkur'),
        ('meðlimir', '0003_alter_meðlimur_options'),
        ('uppskrift', '0004_uppskrift_uppruni_alter_uppskrift_athugasemdir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uppskrift',
            name='flokkar',
            field=models.ManyToManyField(blank=True, to='flokkar.flokkur'),
        ),
        migrations.AlterField(
            model_name='uppskrift',
            name='skodanir',
            field=models.ManyToManyField(blank=True, related_name='medlimaskodanir', through='meðlimir.skodun', to='meðlimir.meðlimur'),
        ),
    ]
