# Generated by Django 4.2.27 on 2025-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flokkur',
            fields=[
                ('nafn', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
