# Generated by Django 4.2.27 on 2025-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flokkar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flokkur',
            options={'verbose_name_plural': 'Flokkar'},
        ),
        migrations.AddField(
            model_name='flokkur',
            name='yfirflokkur',
            field=models.BooleanField(default=False),
        ),
    ]
